Provide a "nla_put_u64" definition.
Was
  drbd-headers\linux/genl_magic_struct.h(78): error C4013:
    'nla_put_u64' undefined; assuming extern returning int