Progress on "drbd_transport_tcp.c".
Now we're seeing that we're too new in some things...
   drbd_transport_tcp.c(66): error C2079: 'waiter' uses
       undefined struct 'drbd_waiter'
because drbd-9 8cacacfbe41d117916cfec0a585b595889549bfd is
    Remove struct drbd_waiter, embed it into drbd_path